# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kal-haj- <kal-haj-@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/08/24 22:03:50 by kal-haj-          #+#    #+#              #
#    Updated: 2025/08/25 20:24:27 by kal-haj-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC	= cc
CFLAGS	= -Wall -Wextra -Werror -D BUFFER_SIZE=42
NAME	= libgetnextline.a
SRC	= get_next_line.c \
		get_next_line_utils.c
BONUS_SRC = get_next_line_bonus.c \
				get_next_line_utils_bonus.c

OBJ	= $(SRC:.c=.o)
BONUS_OBJ	= $(BONUS_SRC:.c=.o)

all:	$(NAME)
$(NAME):	$(OBJ)
	ar rcs $(NAME) $(OBJ)
bonus: $(BONUS_OBJ)
	ar rcs $(NAME) $(BONUS_OBJ)
clean:
	rm -f $(OBJ) $(BONUS_OBJ)
fclean:	clean 
	rm -f $(NAME)
re:	fclean $(NAME)


.PHONY: clean all fclean re
